export interface KnowledgeArticle {
  slug: string;
  title: string;
  categoryId: string;
  who: string;
  when: string;
  replaces: string;
  href: string | null;
  hasVideo: boolean;
  videoSrc: string | null;
  /** Filled from KNOWLEDGE_YOUTUBE_IDS after the article list is defined. */
  youtubeId?: string | null;
  steps: string[];
  doneWhen: string;
  watchOut: string;
  alsoOnThisPage: string[];
}

export interface KnowledgeCategory {
  id: string;
  title: string;
  description: string;
}

/**
 * Unlisted YouTube URLs or 11-character ids, keyed by lesson slug.
 * Example: 'add-unit': 'https://youtu.be/xxxxxxxxxxx'
 */
export const KNOWLEDGE_YOUTUBE_IDS: Record<string, string> = {
  'add-occupant': 'IN-qYShi924',
  'add-office-login': 'qkrJzz6_RcY',
  'add-tenant': 'Ew_3RyOXWM0',
  'add-unit': 'McvsuAgrukw',
  'bills-expenses-reports': 'lX0GBdtqz2c',
  'change-office-password': '6NvK8EMpE7U',
  'chase-payments': 'bvdTolTx12I',
  'check-collections': 'WaOAxNA89EM',
  'close-month': 'r9j6PfozfBI',
  'collect-rent': 'WShYBQGqOO8',
  'confirm-receipt': '1UHtivYOQBM',
  'create-invoice': 'PSTW16mfwNU',
  'design-lease': 'uPVzo2AIwv0',
  'document-categories': 'FLtZBnTX_-s',
  'enter-meter-readings': 'TJSEjkOrp2I',
  'export-data': 'CLT97tvSucs',
  'file-documents': 'HXmdhlGlFMo',
  'financial-dashboard': 'cP-92JxmuiI',
  'generate-all-invoices': 'MhzKTl7DYKY',
  'give-notice': 'J99eLwopLaA',
  'hold-unit': 'THtlumydov4',
  'import-history': 'Dl3-Rm80Cig',
  'issue-lease': '3btZ5xwxuw4',
  'late-fees': '1x54nWpwLHE',
  'lead-to-tenant': 'tU56XdGyNXE',
  'lease-templates': 'AopiniWn_vc',
  'leasing-alerts': 'TbVzwYzsIFY',
  'log-assets': 'VuZ535UYzRM',
  'look-up-activity': '_yyYwBji0AA',
  'move-out': 'ENE2_bKwoKE',
  'office-settings': 'eYt1C-lM8Gk',
  'open-dashboard': 'uGeFv4ed4qQ',
  'payment-gateways': 'ZmFg59NzAoU',
  'pull-report': 'H-Xa-eh0ruk',
  'record-expense': 'xPmk_kBrx2Q',
  'renew-lease': 'fgL3Z-ZYOSQ',
  'send-reminders': 'V6k8t_3ZUyk',
  'split-metered-bill': '7as9dAQkK1o',
  'staff-portal': 'SD_Jrx-UEwA',
  'start-lease': '9PFJ7Izrums',
  'tenant-pay-details': '2223WNwOU7o',
  'tenant-portal': 'F3ox7PMv6rk',
  'unit-groups': 'WG_4fARg8GQ',
  'utility-bill': 'NdTamureuNM',
  'work-repair': 'krgdC5Im1Lk',
};

export function parseYouTubeId(value: string): string | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  if (/^[\w-]{11}$/.test(trimmed)) return trimmed;
  try {
    const url = new URL(trimmed);
    if (url.hostname === 'youtu.be' || url.hostname === 'www.youtu.be') {
      const id = url.pathname.split('/').filter(Boolean)[0];
      return id && /^[\w-]{11}$/.test(id) ? id : null;
    }
    const fromQuery = url.searchParams.get('v');
    if (fromQuery && /^[\w-]{11}$/.test(fromQuery)) return fromQuery;
    const embed = url.pathname.match(/\/(?:embed|shorts)\/([\w-]{11})/);
    return embed?.[1] ?? null;
  } catch {
    return null;
  }
}

export const KNOWLEDGE_CATEGORIES: KnowledgeCategory[] = [
  { id: "core-loop", title: "Core loop", description: "Start here: buildings, tenants, invoices, and collecting rent." },
  { id: "day-to-day", title: "Day to day", description: "Reservations, leases, repairs, documents, and chasing unpaid rent." },
  { id: "month-close", title: "Month close and reports", description: "Collections, disbursement, and exports for the accountant." },
  { id: "utilities-property", title: "Utilities and property extras", description: "Shared bills, meter readings, and unit assets." },
  { id: "setup", title: "Setup", description: "Do once, then as needed: templates, settings, and office logins." },
  { id: "occasional", title: "Occasional / advanced", description: "Bulk invoices, history import, late fees, and staff portal." },
];

export const KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    slug: "add-unit",
    title: "Add or update a building and rooms",
    categoryId: "core-loop",
    who: "Office admin",
    when: "A new building or room is added, or rent / deposit amounts change.",
    replaces: "Excel / notebook lists of units, monthly rates, and deposit rules for Balibago and Villasol.",
    href: "/admin/properties",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/add-unit.webm",
    steps: [
      "Sidebar **Properties** (`/admin/properties`). Click **Add**. **Basic info:** **Building name**, **Building type** (**Residential**, **Commercial**, **Mixed Use**). **Location:** **Region**, **City** (required). **Deposits & advance:** **Deposit type**, **Months of rent** (or **Deposit amount** / **Deposit percentage**), **Minimum deposit floor**, **Advance type**, **Utility deposit amount**. Click **Create building**.",
      "With the building selected, click **Add Room**. **Room number**, **Room type**, **Monthly rate (₱)**. Click **Create room**.",
      "To change a building: **Edit property** → **Update building**. To change a room: open the room → **Edit Room** → **Monthly Rent (₱)** / **Deposit (₱)** → **Save Changes**.",
    ],
    doneWhen: "The building is in the Properties list after refresh. The room shows the rate you entered. Deposit rules appear under **Deposits & advance**.",
    watchOut: "**Create building** needs **Building name**, **Region**, and **City**. Photo upload stays blocked until those are saved.",
    alsoOnThisPage: [
      "**Search** (left list) — placeholder **Search**; finds properties by name. Aria: **Search properties**.",
      "**Sort** — **Name A–Z**, **Name Z–A**, **City A–Z**, **Most vacant**.",
      "**Filter** — **Occupancy**: **All properties**, **Has vacant rooms**, **Fully occupied**.",
      "No pagination on the property list. No bulk edit/delete. No export or print.",
      "**Add** — opens Add building (not a separate page).",
      "Building card: **Rooms** / **Tenants** counts; expand rooms (**Expand rooms** / **Collapse rooms**).",
      "Detail empty state: **Select a property**.",
      "Right rail (**Property actions**): **Record Payment**, **Add note**, **Add Tenant**, **Add Room**, **Maintenance**.",
      "Tabs: **Overview**, **Rooms**, **Maintenance**.",
      "Photo: **Change photo** or **Add property photo**.",
      "**Open on Google Maps** — if a pin is saved.",
      "**Show on landing page** — featured properties and What’s nearby. Blocked when all landing slots are used.",
      "Menu: **Edit property**, **Manage rooms**, **Delete property**.",
      "Overview **Collection of Rent**: **Show by** month; **Rent Outstanding**, **Rent Collected**, **Total Rent**, **Processing**; **Total units**, **Occupied**, **Vacant**, **Unassigned**; table **Vacant units — days vacant & estimated lost rent**.",
    ],
  },
  {
    slug: "add-tenant",
    title: "Put a person in a unit (lease + portal login)",
    categoryId: "core-loop",
    who: "Office admin",
    when: "Someone is already moving in and needs a lease and a login. For a new inquiry, use **Inquiry → occupied unit** instead.",
    replaces: "Excel tenant rows plus a handwritten or Messenger password for the portal.",
    href: "/admin/tenants",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/add-tenant.webm",
    steps: [
      "Sidebar **Tenants** (`/admin/tenants`). Click **Add Tenant**. (From a vacant unit you can click **Add Tenant** on **Properties**; **Property** and **Room** stay locked.)",
      "**Personal Info:** **First Name**, **Last Name**, **Email** (portal login). **Housing:** **Property**, **Room**, **Monthly Rent (₱)**, **Lease Template**. **Lease:** **Lease Start Date**, **Move In Date**.",
      "Click **Create Tenant**. Copy **Temporary password** from **Tenant account created** (also emailed). Click **Continue to tenant**. Give them **Email** + that password and `/auth/signin`.",
    ],
    doneWhen: "The tenant profile opens. After refresh they still appear under **Tenants**, the room is occupied, and they can log in with the email.",
    watchOut: "**Email is required.** **This email is already in use** means pick another. A room also needs **Lease Template**, **Lease Start Date**, and **Monthly Rent (₱)**. Later: profile **Reset password**.",
    alsoOnThisPage: [
      "**Tenants list**",
      "Header: **Reservations**, **Add Tenant**. Description: **Manage your tenant relationships**.",
      "Cards: **Total Tenants**, **Active Tenants**, **Pending Tenants**, **Avg. Income**.",
      "**Search** — **Name, email, phone, or unit...** (name, email, phone, unit/building).",
      "**Building** — **All Buildings**, each property, **Unassigned**.",
      "**Status** — **All Status**, **Current tenants**, **Active**, **Pending**, **Former tenants**.",
      "**Signal** — **All signals**, **Payment confirmation**, **Escalated**, **Overdue**, **Due today**, **Due soon**, **Awaiting payment**, **Partial payment**, **Rent**, **Bills**, **Water**, **Electricity**, **Maintenance**, **New tenant**, **Pending**, **Unsigned lease**, **Unassigned**.",
      "**Sort** — **Payment urgency**, **Due date**, **Last Name**, **First Name**, **Property**, **Email**, **Status**, **Income**, **Move-in Date** (toggle **Sort ascending** / **Sort descending**).",
      "**Group** — **By payment** or **By property**.",
      "Grid / list view. Pagination 40 per page (**Showing {n} of {total} tenants**).",
      "No bulk actions. No export.",
      "Legend: **Overdue**, **Due today**, **Due soon**, **Confirmation**; topics **Rent**, **Bills**, **Water**, **Electricity**, **Maintenance**, **Unsigned**.",
      "**Add Tenant form** (modal; `/admin/tenants/new` also exists)",
      "Sections: **Personal Info**, **Emergency Contact**, **Employment**, **Housing**, **Lease**, **Notes**.",
    ],
  },
  {
    slug: "create-invoice",
    title: "Issue this month’s rent invoices",
    categoryId: "core-loop",
    who: "Office admin",
    when: "Start of the billing period, before you collect rent. One invoice per tenant you expect to pay. To bill everyone at once, see **Generate all rent invoices for the month**.",
    replaces: "Writing a rent row in Excel so there is something to tick when money arrives.",
    href: "/admin/financial/invoices",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/create-invoice.webm",
    steps: [
      "Sidebar **Payments** → **Invoices** (`/admin/financial/invoices`). Click **Create Invoice**.",
      "**Tenant & Room:** **Tenant**, then **Room**. **Billing Period:** **Due Date** (required). Optional: **Billing Period Start**, **Billing Period End**.",
      "**Invoice Items:** **Description**, **Type** (**Rent**, **Utilities**, **Fees**, **Deposit**, **Other**), **Quantity**, **Unit Price**. Click **Create Invoice**.",
    ],
    doneWhen: "The invoice list shows the new row after refresh. **Collect rent** can attach a payment to it.",
    watchOut: "**Please select a tenant**, **Please select a room**, **Please set a due date**, and valid item prices are required. Creating an invoice does not collect money.",
    alsoOnThisPage: [
      "**Invoice Management list**",
      "Description: **Create, track, and collect invoices**.",
      "Cards: **Paid Invoices**, **Unpaid Invoices**, **Overdue**, **Total Invoices**.",
      "**Search** — **Invoice #, tenant...**",
      "Filters: **Status** (**All Statuses**, **Draft**, **Sent**, **Paid**, **Overdue**, **Cancelled**); **Tenant** (**All Tenants**).",
      "Pagination 20 per page. No sort UI. No bulk. No export.",
      "Table: **Open an invoice from the View action.** Empty: **Get started by creating a new invoice**.",
      "**Create Invoice form**",
      "Nav: **Tenant**, **Dates**, **Items**, **Notes**.",
      "**Add Item** / **Remove** for extra lines. **Notes** optional.",
      "**Cancel**.",
      "**Invoice detail** (`/admin/financial/invoices/[id]`)",
      "**Back to invoices**. **Record Payment**. **Fully paid** (disabled when already paid). **View Tenant Profile**. **Print Invoice**.",
      "Sections: **Invoice Details**, **Line Items**, **Payment History**, **Status**, **Amount Summary**, **Invoice Statistics**, **Billing agreements**.",
    ],
  },
  {
    slug: "tenant-pay-details",
    title: "Put the GCash / bank number on Pay online",
    categoryId: "core-loop",
    who: "Office admin",
    when: "Before tenants use portal **Pay now**. After the number or account name changes.",
    replaces: "Sending the office GCash number by chat every time a tenant asks how to pay.",
    href: "/admin/settings?tab=payments",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/tenant-pay-details.webm",
    steps: [
      "Sidebar **Payments** → **Tenant pay details** (`/admin/settings?tab=payments`). (Header gear → tab **Tenant payments** is the same page.)",
      "Fill **Payment phone number** (required). Optional: **Account name**, **Bank name (optional)**, **Bank account number (optional)**, **Instructions shown to tenants**.",
      "Under **Accepted methods** tick **GCash**, **Maya**, **Bank transfer**, and/or **Other e-wallet**. Click **Save payment details**.",
    ],
    doneWhen: "You see **Payment instructions saved — tenants will see these on Pay.** After refresh the same number is still there. A tenant on **Pay online** sees that phone / account.",
    watchOut: "**Payment phone number** is required to save. If this is empty, portal **Pay now** is blocked. Use **Collect rent** or **Confirm a receipt** after they pay.",
    alsoOnThisPage: [
      "**This tab**",
      "Heading **Tenant payment destination**.",
      "Alert if empty: **Tenants cannot Pay online yet**.",
      "Placeholder **09XXXXXXXXX**. Hints: **GCash / Maya / mobile number that receives tenant payments**, **Name on the GCash / bank account**, **e.g. BPI, BDO**.",
      "Saving: **Saving...**. Success: **Payment details saved** / **Tenants can now see where to send GCash / transfers.**",
      "No search / list / export on this tab.",
      "**Other Settings tabs** (header gear → `/admin/settings`)",
      "**Notifications** — **In-app** / **Email** per category.",
      "**Security** — **Two-Factor Authentication**, **Session Timeout**, **Change Password**.",
      "**Preferences** — Language, Timezone, Currency, Date Format.",
      "**System** — **Enable tenant portal**, **Enable late-fee penalties**, nearby map cache, **Clear Cache**, **Export Data**.",
      "Footer **Save Settings** on non-payments tabs.",
      "See **Set office preferences**.",
      "**Related**",
    ],
  },
  {
    slug: "collect-rent",
    title: "Collect rent (record a payment against an invoice)",
    categoryId: "core-loop",
    who: "Office admin / Owner",
    when: "You received cash, GCash, Maya, bank, or cheque in the office and need it on the books. If the tenant uploaded a receipt, use **Confirm a tenant’s uploaded GCash receipt** instead.",
    replaces: "GCash screenshot in Messenger, then a tick on the Excel ledger.",
    href: "/admin/financial/payments",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/collect-rent.webm",
    steps: [
      "Sidebar **Payments** (`/admin/financial/payments`). Click **Process Payment**. Choose **Property**, optional **Room**, then **Tenant**. Click **Continue**.",
      "**1. Select invoice to pay** — click one invoice row. **2. Enter payment details:** **Mode of Payment** (**Cash**, **Cheque**, **Bank transfer**, **GCash**, **Maya**, **Other**), **Payment Date**, **Amount Received**. Optional: **OR Date**, **Notes (optional)**, **Upload Proof of Payment** (**Take photo** or **Choose file**).",
      "Click **Confirm Payment**, then **Yes, Confirm Payment**.",
    ],
    doneWhen: "You land on the payment receipt. After refresh, **Payments** shows **Paid** or **Partially paid** for that invoice.",
    watchOut: "**Confirm Payment** stays off until an invoice is selected and **Amount Received** is greater than 0. There must already be an invoice — create one first if you see **No unpaid invoices for this tenant.**",
    alsoOnThisPage: [
      "**Payments list**",
      "Description: **Review tenant receipts, confirm collections, and follow up on open invoices.**",
      "Banner if pay details missing: **Tenant Pay now is blocked** → **Add tenant pay details**.",
      "Cards: **Outstanding**, **Collected**, **Overdue**, **Pending verification**.",
      "**Pending verification** — receipts waiting for office confirmation. Badge **Pending**. Open a row to **Confirm payment** / **Reject** (see confirm-receipt). Empty: **No payments waiting for verification.**",
      "**Search** — **Tenant, unit, or invoice**.",
      "Filters: **Due date** (**Upcoming month**, **Overdue**, **This week**, **This month**, **Next 30 days**, **Past due dates**, **All due dates**); **Property** (**All properties**); **Type** (**All types**, **Rent**, **Utilities**, **Deposit**, **Penalty**, **Other**); **Status** (**All statuses**, **Unpaid**, **Partially paid**, **Paid**, **Overdue**); **Payment period**.",
      "Table **Collections**. Row statuses: **Paid**, **Partially paid**, **Overdue**, **Unpaid**.",
      "Pagination 10 per page (**Previous** / **Next**).",
      "No column sort. No bulk actions. No export. No Clear filters button.",
      "Empty: **Process Payment**.",
      "**Process Payment** (`/admin/financial/payments/new`)",
      "One invoice at a time (**Only one invoice can be selected for payment at a time.**).",
      "Empty invoices: **No unpaid invoices for this tenant.**",
    ],
  },
  {
    slug: "confirm-receipt",
    title: "Confirm a tenant’s uploaded GCash receipt",
    categoryId: "core-loop",
    who: "Office admin / Owner",
    when: "The tenant used **Pay now** or **Upload receipt** in the portal, and **Payments** shows **Pending verification**.",
    replaces: "Checking a screenshot in Messenger, then ticking Excel.",
    href: "/admin/financial/payments",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/confirm-receipt.webm",
    steps: [
      "Sidebar **Payments** (`/admin/financial/payments`). Under **Pending verification**, open the tenant’s row (badge **Pending**).",
      "Check the attached receipt photo if there is one. Click **Confirm payment**.",
      "Optional: type the **GCash / bank reference**. Click **Confirm received**. Use **Reject** only if the claim is wrong.",
    ],
    doneWhen: "Toast **Payment confirmed**. After refresh the row is gone from **Pending verification**, and the invoice shows **Paid** (or **Partially paid**).",
    watchOut: "**Confirm payment** only appears while status is **pending**. If a reference is already on file and you type a different one: **Reference mismatch** — leave the box blank to confirm anyway.",
    alsoOnThisPage: [
      "**Payments list (same screen as Collect rent)**",
      "Card **Pending verification** — **Receipts waiting for office confirmation**.",
      "Section copy: **Cross-check the receipt if one is attached, then confirm. Reference number is optional for now — ledger imports often have none.**",
      "Compact **Confirm** / **Reject** may appear on the hub; full labels **Confirm payment** / **Reject** on the receipt.",
      "Search, filters, pagination — see **Collect rent**. Invoice balances do **not** change until you confirm.",
      "**Payment detail**",
      "Alert **Awaiting verification**.",
      "**Confirm payment received** dialog: invoice / transaction / reference lines; **GCash / bank reference (optional)**; **Confirm received**.",
      "**Reject payment claim** → **Reject**.",
      "**Tenant conversation** — **Message the tenant…**; needs a message or photo.",
      "**Uploaded receipt** / **Download proof**.",
      "After confirm, **Refund** / **Void** apply like office-recorded payments.",
      "**Not this job**",
      "**Process Payment** is for cash you enter yourself.",
    ],
  },
  {
    slug: "utility-bill",
    title: "Split a utility bill across rooms",
    categoryId: "core-loop",
    who: "Office admin",
    when: "A building-wide electric or water bill arrives. For meter-by-meter splits, see **Split a metered bill by readings**.",
    replaces: "Calculator + Excel split of one Meralco or water bill across occupied rooms (vacant share absorbed by the owner).",
    href: "/admin/bills-expenses/utility-bills",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/utility-bill.webm",
    steps: [
      "Sidebar **Bills & Expenses** → **Utility Bills** (`/admin/bills-expenses/utility-bills`). Click **Add Bill**.",
      "**Location:** **Scope** = **Building-wide (common area)**, choose **Building**. **Utility:** **Utility Type** (**Electric** or **Water**), **Allocation method** = **Shared — manual split**. Check **Equal-split across units (creates a per-room share; vacant rooms are owner-absorbed)**. Optional: **Unit group (preferred)** or **Floor filter**. **Period:** **Billing Period Start**, **Billing Period End**, **Due Date**. **Amount:** enter **Amount**.",
      "Click **Create Bill**.",
    ],
    doneWhen: "The bill appears on **Room Utility Bills**. After refresh, each included room has its share; vacant rooms are owner-absorbed.",
    watchOut: "**Amount must be greater than 0.** Building-wide bills need **Building**. **Specific unit / room** does not split. Dates: start, end, and due are required; end must be on or after start.",
    alsoOnThisPage: [
      "**Room Utility Bills list**",
      "Cards: **Total Amount**, **Pending**, **Paid**, **Overdue**.",
      "**Search** — **Room, building, provider...**",
      "Filters: **Building** (**All Buildings**); **Utility Type** (**All Types**, **Electricity**, **Water**); **Status** (**All Status**, **Pending**, **Paid**, **Overdue**, **Disputed**); **From Date**, **To Date**.",
      "Pagination 20 per page. No sort. No bulk. No export or print.",
      "Row icons: **Mark as Paid** (confirm: **Mark bill as paid?** — **This marks the utility bill paid. It does not record a tenant payment.**), **Delete** (confirm: **Delete bill?**).",
      "Empty: **Get started by adding a new bill**.",
      "**Add Bill form** (also `/admin/bills-expenses/utility-bills/new`)",
      "Sections: **Location**, **Utility**, **Period**, **Amount**, **Status**, **Notes**.",
      "**Scope: Specific unit / room** — pick **Unit / Room**; that path does **not** split.",
      "Other **Allocation method**: **Submetered (per-unit meter)**, **Not applicable (own account)**.",
      "**Unit group (preferred)** — **None — use floor / all units**. Create groups under **Bills & Expenses → Unit groups**.",
      "**Floor filter (optional)** — **All floors** or a floor (e.g. Balibago 3rd-floor shared water).",
      "**Provider / vendor**, **Account Number**, meter **Previous meter reading** / **Current meter reading**, **Usage unit**.",
    ],
  },
  {
    slug: "record-expense",
    title: "Record a building expense",
    categoryId: "core-loop",
    who: "Office admin / Owner",
    when: "You paid a vendor or staff and need it on the month’s cash-flow.",
    replaces: "A cash-out row in Excel (salary, repair, fuel, cleaning).",
    href: "/admin/financial/expenses",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/record-expense.webm",
    steps: [
      "Sidebar **Bills & Expenses** → **Expenses** (`/admin/financial/expenses`). Click **Record Expense**.",
      "**Amount:** enter **Amount**. **Category:** choose **Category** and **Description**. **Date:** set **Expense Date**.",
      "Optional: **Building**, **Unit / Room**, **Vendor**. Click **Record Expense**.",
    ],
    doneWhen: "You land on the expense detail. After refresh it appears on **Expenses**. It will count in **Disbursement / Cash-flow**.",
    watchOut: "**Amount must be greater than 0.** Pick a **Category** that matches the spend (e.g. **Staff salary**, **Food allowance**).",
    alsoOnThisPage: [
      "**Expenses list**",
      "Cards: **Total Amount**, **This Month**, **Top Category**, **Average**.",
      "**Search** — **Description or vendor...**",
      "Filters: **Category** (**All Categories**), **Building** (**All Buildings**), **Vendor**, **From Date**, **To Date**.",
      "Table **Actions** → **View**. No export on this list. No bulk. No sort UI called out.",
      "Empty: use **Record Expense**.",
      "**Record Expense form**",
      "Sections: **Amount**, **Category**, **Date**, **Location**, **Vendor**, **Notes**.",
      "**Category** options: **Cleaning**, **Maintenance**, **Repair**, **Upgrade**, **Garbage collection**, **Food allowance**, **Fuel / diesel**, **Staff salary**, **Refund**, **Cash allowance**, **Other**.",
      "**Vendor** can be **Add vendor** / type a name.",
      "**Expense detail** (`/admin/financial/expenses/[id]`)",
      "**Edit Expense** (`.../edit`). **Delete** — confirm **Delete expense?** / **Delete this expense? This cannot be undone.**",
      "**Related**",
      "Counts in **Disbursement / Cash-flow**.",
    ],
  },
  {
    slug: "issue-lease",
    title: "Issue or store a lease document",
    categoryId: "core-loop",
    who: "Office admin",
    when: "After a tenant is assigned to a unit, or when a signed copy comes back.",
    replaces: "Printed contract in a folder, or a signed PDF in Messenger / Drive.",
    href: "/admin/tenants",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/issue-lease.webm",
    steps: [
      "Sidebar **Tenants** → open the tenant → **Documents** (`/admin/tenants/[id]?tab=documents`).",
      "Under **Upload / e-sign lease**, click **Generate lease** (draft from assignment and building policies) or **Upload** / **Upload signed PDF** (PDF, DOC, or DOCX, max 10MB).",
      "If e-sign is needed, type the name, accept the terms, and click **Sign as landlord** (or **Sign lease**). Use **Regenerate lease** only if you must replace the file.",
    ],
    doneWhen: "**Lease Contract** under **Required Documents** shows the file after refresh. The tenant can open it under portal **Documents**.",
    watchOut: "**Generate lease** needs an active room assignment. If a signed lease is already on file, the app asks to confirm replace before overwriting. Sign needs a typed name and the agreement checkbox.",
    alsoOnThisPage: [
      "**Documents tab (this job)**",
      "**Required Documents:** **Lease Contract**, **ID Requirements**, **Proof of Residency**.",
      "Empty lease: **No lease agreement on file** / **Generate a draft from lease data, or upload a signed PDF.**",
      "After a file: **Lease agreement on file**; **View**, **Delete**.",
      "**Sign as landlord**, **Sign as witness**; **Type your full legal name**; checkbox agreeing to terms; **Sign lease**; **View lease**.",
      "Status: **Tenant signed** / **Awaiting tenant**; **Landlord signed** / **Awaiting landlord**.",
      "**Optional Documents** / **Add Document** — table **Full Name**, **ID Type**, **File**, **Actions**. Pagination 5 per page. Empty: **No optional documents yet.**",
      "No search / filter / sort / export / print on this tab.",
      "Delete confirm: **Delete document?**",
      "Replace confirm if already signed: **Replace signed lease?** → **Replace & generate**.",
      "Upload errors: **Invalid File**, **File Too Large** (10MB).",
      "**Same tenant, other tabs (not this job)**",
      "Profile, Lease, Financials — see **Add Tenant**.",
      "**Sidebar Documents** (`/admin/documents`) — separate library, not this tab",
    ],
  },
  {
    slug: "lead-to-tenant",
    title: "Inquiry → occupied unit (leasing pipeline)",
    categoryId: "core-loop",
    who: "Office admin",
    when: "Someone asks about a vacant unit and you need to track them through viewing, payment, and lease. If they are already moving in today, use **Add Tenant** instead.",
    replaces: "Facebook / walk-in notes, then a later Excel move-in when they actually take the room.",
    href: "/admin/tasks",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/lead-to-tenant.webm",
    steps: [
      "Sidebar **Tasks** (`/admin/tasks`, board **Onboarding**). Click **Add opportunity**.",
      "**Contact:** **First name**, **Last name**, **Email**, **Phone**. **Property:** **Building**, **Room**, **Monthly rent (₱)**. Save with **Create opportunity**. Drag or **Move to stage…** through **New inquiry** → **Viewing scheduled** → **Viewing done** → **Documents** → **Background check** → **Awaiting signature**.",
      "Open the card → **Payment**: check **Payment received**. **Lease:** **Lease Start Date** and **Lease Template**, then **Generate lease**. The card moves to **Lease signed**.",
    ],
    doneWhen: "After refresh, the person is on **Tenants**, the room is occupied, and the card is in **Lease signed**.",
    watchOut: "**Generate lease** stays off until **Building**, **Room**, and **Payment received** are set. **Email is required to generate a lease.** Do this on **Onboarding**, not the Payments board.",
    alsoOnThisPage: [
      "**Board chrome**",
      "Boards: **Onboarding** (this job), plus **Payments** and **Building expenses** (and maintenance follow-up). Switch boards at the top.",
      "**Search Opportunities**. **Sort** (cycles updated / title / amount / due). **Kanban view** / **List view**.",
      "**Advanced Filters:** **Stage**, **Assignee** (**Anyone** / **Unassigned**), **Building**, **Tag**, **Amount min** / **Amount max**, **Due from** / **Due to**. **Clear filters**.",
      "**Import** — dialog **Import CSV · {board}**. Columns: title, first_name, last_name, email, phone, amount, notes, tags, due_at, source, stage. Max 200 rows. **Load sample row**.",
      "**Bulk Actions:** **Select all**, **Move to stage…**, **Delete ({n})** (confirm cannot be undone).",
      "**Configure stages**, **New board**, overflow **Sync pipelines**, **Manage Fields**.",
      "Archive board: **Archive board?** (can **Unarchive** later).",
      "No pagination. No export or print.",
      "Suggested tags: **Hot lead**, **Docs complete**, **Awaiting ID**, **Awaiting income proof**, **BG pending**, **Lease out**, **Budget concern**, **Referral**, **Call back**, **Viewing scheduled**.",
      "**Add opportunity form**",
      "Sections: **Contact**, **Property**, **Schedule**, **Documents**, **Screening**, **Payment**, **Lease**, **Status**, **Tags**, **Notes** (**History** when editing).",
      "**Which unit are you interested in?** can stay **Not sure yet / general inquiry**.",
      "**Schedule:** **Source**, **Viewing date & time**, **Viewing status** (**Not set**, **Scheduled**, **Completed**, **No-show**, **Rescheduled**, **Cancelled**). Saving a viewing date moves the card to **Viewing scheduled**.",
    ],
  },
  {
    slug: "add-occupant",
    title: "Add a roommate / occupant",
    categoryId: "core-loop",
    who: "Office admin (tenant can also add occupants in the portal)",
    when: "Someone else lives in the unit besides the person on the lease.",
    replaces: "A handwritten extra name on the Excel tenant row (spouse, child, relative — not the lease holder).",
    href: null,
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/add-occupant.webm",
    steps: [
      "Sidebar **Tenants** → open the tenant → **Profile**. Under **Occupants**, click **Add Occupant** (opens the occupied room). Or: **Properties** → open that room.",
      "Under **Current Tenant**, click **Add Occupant**.",
      "Fill **First Name**, **Last Name**, and **Move-in Date**. Click **Add Occupant**.",
    ],
    doneWhen: "Toast **Occupant added successfully!** After refresh the name is on the room and on the tenant **Occupants** list.",
    watchOut: "The unit must already have a current tenant. Profile **Add Occupant** only jumps to the room — the form is on the room.",
    alsoOnThisPage: [
      "**Add Occupant modal**",
      "Copy: **Add a non-tenant occupant (e.g., relative, spouse, child) to this room.**",
      "Optional: **Relationship to Tenant** (**Spouse**, **Child**, **Parent**, **Sibling**, **Relative**, **Friend**, **Other**), **Date of Birth**, **Phone**, **Email**.",
      "**Emergency Contact (Optional):** **Contact Name**, **Contact Phone**, **Relationship**.",
      "**Notes**. **Cancel**.",
      "Toast: **Occupant added successfully!**",
      "**Room**",
      "Card **Other Occupants**. **Tenancy History** is lease history, not occupant history.",
      "**Tenant Profile Occupants table**",
      "Columns: **Full Name**, **Contact Details**, **Address**, **Relationship to Tenant**, **Actions**.",
      "Empty: **No occupants on file. The primary tenant is listed on the lease.**",
      "Occupant ⋯ actions on the tenant list do not edit yet — change occupants from the room.",
      "**Tenant portal**",
      "**Profile** → **Occupants**: **Add Occupant** / **Update Occupant**. Required: first name, last name, move-in date.",
    ],
  },
  {
    slug: "move-out",
    title: "Move-out (unit becomes vacant, history retained)",
    categoryId: "core-loop",
    who: "Office admin",
    when: "The tenant’s last day; the room must be free for the next occupant. To end the contract on paper without emptying the room, use **Give notice (terminate on paper)** instead.",
    replaces: "Crossing the name off Excel and leaving the unit “empty” in the notebook, while keeping past occupancy.",
    href: "/admin/leasing",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/move-out.webm",
    steps: [
      "Optional inspection worksheet: **Leasing** → **Move-outs** → **Start move-out** (also on the lease detail). Pick **Occupied lease** and **Planned move-out date**. This does **not** empty the room.",
      "To vacate: **Properties** → open the occupied room (`/admin/rooms/[id]`), or **Leasing** → open the lease. Under **Tenant assignment** / **Current Tenant**, click **End Assignment**.",
      "In **End Tenant Assignment**, set **End Date**, optional **Notes**, then **End Assignment**. If a worksheet is open: **Move-outs** → fill **Actual move-out date** and refund fields → **Finalize move-out & refund**.",
    ],
    doneWhen: "After refresh the room is vacant and the person still appears in tenant / lease history. Toast: **Tenant unassigned successfully!** (End Assignment) or **Move-out finalized**.",
    watchOut: "**End Date** is required. **Terminate** only ends the contract on paper (**Notice given**). The unit stays occupied until **End Assignment** or **Finalize**. **Start move-out** alone does not vacate.",
    alsoOnThisPage: [
      "**Leasing** (`/admin/leasing`)",
      "Title: **Tenant room assignments, renewals, and move-outs**.",
      "Tabs: **All leases**, **Expiration alerts**, **Renewals**, **Move-outs**.",
      "Header: **New tenant**, **New lease**; on Move-outs: **Start move-out**; on Alerts: **Generate Alerts**.",
      "Leases search: **Tenant, unit...** **Status:** **All Status**, **Active**, **Expiring soon**, **Notice given**, **Draft**, **Terminated**. **Building:** **All Buildings**. Pagination on leases. No sort / bulk / export / print.",
      "Summaries: **Active**, **Expiring soon**, **Notice given** (**ended on paper, still occupying**), **Draft**, **Terminated**.",
      "Move-outs empty: **Start a move-out to open the inspection worksheet. The unit stays occupied until you finalize.**",
      "**Start move-out**",
      "**Creates the inspection worksheet. The room stays occupied until you finalize move-out.**",
      "Reuses an open worksheet if one already exists.",
      "**Inspection** (`/admin/leasing/moveouts/[id]`)",
      "**Held funds:** **Security deposit**, **Advance**, **Utility deposit**, **Total held**.",
      "Checklist: **Item**, **Finding** (**Pending**, **Pass**, **Fail / deduct**, **N/A**), **Deduction (₱)**, **Notes**. **Use checklist totals in refund fields**. **Save inspection**.",
      "Fields: **Inspection notes**, **Actual move-out date**, **Deposit return**, **Deposit deduction**, **Advance return**, **Utility deposit return**, **Deduction reason**.",
    ],
  },
  {
    slug: "tenant-portal",
    title: "Tenant self-serve (unit, balance, docs, maintenance)",
    categoryId: "core-loop",
    who: "Tenant (office can **Preview portal** from the tenant profile)",
    when: "After the office creates the account and shares **Email** + **Temporary password**.",
    replaces: "Asking the office for balance, photos of the lease, and repair requests by chat.",
    href: "/auth/signin",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/tenant-portal.webm",
    steps: [
      "Open `/auth/signin`. Enter **Email or username** and **Password**. Click **Login**.",
      "First visit: complete **Set up your account** (**First name**, **Last name**, **Email**, **Phone number**, **Current password**, **New password**, **Confirm new password**) and click **Save and continue**.",
      "**Home** shows **Your unit**. **Payments** → **Overview & balance** for amount due; **Pay now** (only after the office saved a GCash / bank number) or **Upload receipt** then **Submit for verification**. **Documents** → **Download**. **Maintenance** → **New ticket** → **Subject**, **Category**, **Details** → **Submit ticket**.",
    ],
    doneWhen: "After refresh, **Home** still shows the unit and balance. A submitted ticket appears under **Maintenance**. Uploaded receipts show under **Payments** → **History**.",
    watchOut: "Wrong login: **Invalid email, username, or password**. **New password** must be at least 8 characters and match **Confirm new password**. Lost password: office **Reset password**. **Pay now** stays blocked until **Tenant pay details** has a phone number.",
    alsoOnThisPage: [
      "**Sign-in**",
      "**Remember me**. **Forgot Password?** → `/auth/forgot-password`. **Register here** (public signup). Error: **Invalid email, username, or password**.",
      "**Home** (`/tenant`)",
      "Due banner; **Pay now** or **View payments**. Cards: **Your unit**, **Monthly rent**, deposit/advance. **Quick actions:** **Documents**, **Maintenance**, **My profile**, **Statements**. **Recent payments**, **Your tickets**. No search on Home.",
      "**Payments** (`/tenant/payments`)",
      "Tabs: **Overview & balance**, **Pay online**, **Upload receipt**, **History**, **Statements** (badge **PDF / Excel**).",
      "Overview: **Total paid**, **Next due**, **Past due**, **Deposit held**, **Advance paid**; **Payment Schedule**; **Pay** / **Pay partial**.",
      "**Pay online** sub-tabs: **Rent Payment**, **Deposit & Advance**, **Utility Deposit**, **Manual Entry**. Form: **Send payment here**, **Mobile / GCash number**, **Select invoice to pay**, **Payment amount (₱)**, **How did you pay?**, **GCash / bank reference**, **Submit payment + receipt**. If the office has no number: **Pay now is unavailable**.",
      "**Upload receipt:** **Link to payment date**, **Payment date**, **Amount (₱)**, **Reference / transaction number**, **Submit for verification**.",
      "**History:** search **Search payments...**; **All Payments** / **Paid** / **Partial**; **Track** / **Message**, **Print**, **Upload**.",
      "**Statements:** **Statement type** (**Payment history**, **Invoice history**, **Financial summary**), **From**, **To**, **Generate statement**; **Excel**, **PDF**, **Print**.",
      "No card checkout, no autopay.",
      "**Documents**",
      "Search **Search documents...**; **Category** (**All Categories**, **Lease**, **Payment**, **Maintenance**, **Insurance**, **Legal**, **Other**). **Preview**, **Download**, **Clear filters**. Tenant cannot upload or delete here.",
    ],
  },
  {
    slug: "open-dashboard",
    title: "Open the office home and clear the day’s work",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "Start of the day, or whenever you sit down at the desk.",
    replaces: "A paper sticky + scanning Excel to see who still owes and which rooms are empty.",
    href: "/admin",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/open-dashboard.webm",
    steps: [
      "Sidebar **Dashboard** (`/admin`). Read the greeting and the **Quick links** / needs-attention cards (overdue, inquiries, tickets).",
      "Use the right rail (**Dashboard actions**): **Record Payment**, **Add note**, **Add Tenant**, **Add Room**, **Maintenance**.",
      "Open a card or **Recents** item to finish that task. Optional: **Manage widgets** to show/hide **Quick links**, **Portfolio ledger**, **Recents**, **Your stickies**.",
    ],
    doneWhen: "You can name what still needs attention today, and a rail action (payment / tenant / room / ticket) opens the matching form.",
    watchOut: "The rail **Add Tenant** badge is vacant-room count, not a to-do list. Clearing a card means doing the job on that screen, then refreshing Dashboard.",
    alsoOnThisPage: [
      "**Add quick link** — presets **Properties**, **Tenants**, **Invoices**, **All tasks**.",
      "**Portfolio ledger** — occupancy / collections snapshot; **Needs attention** block.",
      "**Your stickies** — personal notes on the home screen.",
      "**Recents** — last records you opened.",
      "Header **Search** (properties, tenants, rooms, assets, invoices, documents, leases, payments, expenses). Notification bell. Gear → Settings. **Sign Out**.",
      "No search bar on the home widgets themselves. No export/print of the dashboard.",
      "This is not **Financial Dashboard** (`/admin/financial/dashboard`) — that is charts under Payments.",
    ],
  },
  {
    slug: "hold-unit",
    title: "Hold a unit (reservation)",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "Someone paid a reservation deposit and you need the room held until they sign.",
    replaces: "A verbal “hold” on a vacant room plus a deposit screenshot, before a full lease.",
    href: "/admin/tenants/reservations",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/hold-unit.webm",
    steps: [
      "Sidebar **Tenants** → **Reservations** (`/admin/tenants/reservations`), or **Reservations** on the Tenants page. Click **Create Reservation**.",
      "**Room**, **Tenant** (or **New Tenant**), **Reservation Date**, **Expiry Date**, **Monthly Rate**, **Reservation Deposit**. Optional: **Advance Payment**, **Utility Deposit**, **Notes**. Click **Create Reservation**.",
      "When they take the unit: open the row → **Convert** / **Convert to Assignment**. Set **Lease Start Date** and **Lease Template**. Click **Convert to Assignment**.",
    ],
    doneWhen: "After refresh the reservation is **Active**, or after convert the person is on **Tenants** and the room is occupied.",
    watchOut: "**Reservation deposit required.** Convert needs **Lease Template**. Cancel cannot be undone. This is not **Add Tenant** — convert when they actually move in.",
    alsoOnThisPage: [
      "Cards: **Active Reservations**, **Expired**, **Expiring Soon**, **Converted**.",
      "**Search** — **Search by tenant, room, or building...**",
      "**Status:** **All Statuses**, **Active**, **Converted**, **Expired**, **Cancelled**.",
      "**Sort:** **Sort by Expiry Date**, **Reservation Date**, **Tenant**, **Room**, **Monthly Rate**. Button **Sort**.",
      "Row: **Convert**, **Cancel**. Detail: **Convert to Assignment**, **Cancel Reservation**, **Back to List**.",
      "Convert extra: **Lease End Date (Optional)**, deposits, **Automatically generate invoices for the lease period**, **Notes**.",
      "Cancel confirm: **Cancel reservation?** — **This action cannot be undone.** Confirm **Cancel reservation**. The app refunds the deposit on cancel (no separate **Refund** button).",
      "No pagination called out. No bulk. No export/print.",
    ],
  },
  {
    slug: "start-lease",
    title: "Start a lease from Leasing",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "The person already exists without a current room, and a vacant unit is ready. New people: use **Add Tenant** or **New tenant** instead.",
    replaces: "Writing a new occupancy line in Excel for someone who is already in Tenants but not in a room.",
    href: "/admin/leasing",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/start-lease.webm",
    steps: [
      "Sidebar **Leasing** (`/admin/leasing`). Click **New lease**.",
      "Fill **Tenant**, **Property**, **Room**, **Lease template**, **Start date**, **Monthly rent (₱)**. **End date** fills from the template (or stays open-ended).",
      "Click **Create lease**.",
    ],
    doneWhen: "Toast **Lease created** (or the API success message). You land on the lease detail. After refresh the room is occupied.",
    watchOut: "**Select a lease template.** Only unassigned tenants appear — if they already occupy a unit, **End Assignment** first or use **Add Tenant** for a new person. This does not email a temporary password.",
    alsoOnThisPage: [
      "Dialog: **Assign an existing tenant to a vacant room. Use New tenant if they are not in the system yet.**",
      "**Cancel**. **Lease Template Summary** after you pick a template.",
      "Tenant list is only people **without a current room**. Empty: **No unassigned tenants.**",
      "Rooms: vacant only. **No vacant rooms** if the property is full.",
      "**New tenant** on the same page runs Add Tenant.",
      "Tabs **All leases**, **Expiration alerts**, **Renewals**, **Move-outs** — see those jobs.",
      "Search **Tenant, unit...**; **Status**; **Building**. Pagination on leases. No bulk/export/print.",
      "Lease detail: **Start move-out**, **Terminate**.",
    ],
  },
  {
    slug: "give-notice",
    title: "Give notice (terminate on paper)",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "They gave notice (or you ended the term) but they have not left yet. The room must stay occupied until move-out day.",
    replaces: "Writing a move-out date in the notebook while the tenant still lives there.",
    href: null,
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/give-notice.webm",
    steps: [
      "Sidebar **Tenants** → open the tenant. Summary **Lease** → **Terminate**. Or **Leasing** → open the lease → **Terminate**. (Profile link uses `?action=terminate`.)",
      "In **Terminate lease**, set **Planned move-out date**. Optional: **Reason (optional)**.",
      "Click **Terminate**.",
    ],
    doneWhen: "After refresh the lease shows **Notice given**. The room is still occupied. **Planned move-out date** is saved.",
    watchOut: "**Move-out date required.** If you meant to free the room today, do **End Assignment** instead — **Terminate** will leave them in the unit.",
    alsoOnThisPage: [
      "Dialog copy: **End {name}'s contract on paper. This does not empty the unit.**",
      "Success: **Lease ended on paper** / **The unit stays occupied until End Assignment or Finalize move-out.**",
      "Leasing list status **Notice given** — **ended on paper, still occupying**. Filter **Notice given**.",
      "This is not **End Assignment** and not **Finalize move-out** (those vacate — see **Move-out**).",
      "No search on the dialog.",
    ],
  },
  {
    slug: "renew-lease",
    title: "Renew a tenant’s lease",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "The current term is ending and they are staying.",
    replaces: "Extending the end date on Excel and collecting another deposit/advance by hand.",
    href: "/admin/leasing",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/renew-lease.webm",
    steps: [
      "Sidebar **Tenants** → open the tenant → **Lease**. Click **View** on the current row, then **Renew**. Or summary **Lease** → **Renew**. URL: `/admin/tenants/[id]/leases/[leaseId]/renew`.",
      "Review **Lease Information** / **Renewal Options**: **Retain previous lease details**, **Carry over deposit**, **Waive advance payment**, **Waive any accrued penalties**, **Waive outstanding balance**. Set **Lease Template**, **Rent Amount**, **Start Date**, **End Date**.",
      "Click **Renew lease**, then confirm **Renewing this lease will update the tenant's records and apply the selected settings. Proceed?**",
    ],
    doneWhen: "After refresh **Lease History** shows the new term. Rent and dates match what you saved.",
    watchOut: "**Property, unit, and dates are required.** **Please select a lease template.** Waive options change cash expected — do not tick **Waive outstanding balance** unless you mean to.",
    alsoOnThisPage: [
      "Heading **Renew Lease** / **Renewing lease for:**",
      "Sections: **Lease Details**, **Lease Duration**, **Financial Summary** (**Deposit Amount**, **Advance Amount**, **Initial Cashout**, **First Due Date**).",
      "**Cancel**. Saving state **Renewing…**",
      "Edit (not renew): **Edit Lease** → **Save changes** → **Confirm Lease Changes** (requires **Reason**).",
      "Leasing **Renewals** tab lists leases nearing end — it does not renew by itself.",
    ],
  },
  {
    slug: "leasing-alerts",
    title: "Warn which leases expire soon",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "Monthly, before terms run out.",
    replaces: "A calendar note of end dates.",
    href: "/admin/leasing",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/leasing-alerts.webm",
    steps: [
      "Sidebar **Leasing** (`/admin/leasing`). Open **Expiration alerts**.",
      "Click **Generate Alerts**.",
      "Work the list (renew or give notice). **Renewals** tab lists leases nearing end.",
    ],
    doneWhen: "After refresh, alerts match leases that are actually ending. You have opened **Renew** or **Terminate** for each one you will act on.",
    watchOut: "**Generate Alerts** is a list, not a message to the tenant. **Notice given** is terminate-on-paper, not expiry.",
    alsoOnThisPage: [
      "**All leases** / **Move-outs** — other jobs.",
      "Filters on **All leases**: **Status** includes **Expiring soon**.",
      "Generating alerts does not renew or vacate.",
      "No export/print of the alert list.",
    ],
  },
  {
    slug: "work-repair",
    title: "Work a repair ticket",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "A tenant submitted **New ticket**, or you see an **Open** request.",
    replaces: "A Messenger thread about a leak or broken fixture, with no status in the office.",
    href: "/admin/maintenance",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/work-repair.webm",
    steps: [
      "Sidebar **Maintenance** (`/admin/maintenance`). Open a row (or use **Open pipeline** for the Tasks board).",
      "Set **Status** (**Open**, **In Progress**, **Resolved**, **Cancelled**) and **Priority** (**Low**, **Medium**, **High**, **Urgent**). Optional: **Scheduled Date**, **Completed Date**, **Assigned To**, **Internal notes**.",
      "Click **Save Changes**.",
    ],
    doneWhen: "After refresh the list shows the new **Status**. **Resolved** matches the pipeline **Resolved** column.",
    watchOut: "This page has no **New ticket** button. Do not use **Cancelled** unless the work will not happen.",
    alsoOnThisPage: [
      "**Maintenance Requests list**",
      "Cards: **Total Requests**, **Open**, **In Progress**, **Resolved**.",
      "**Search** — **Ticket, title, tenant, building…**",
      "Filters: **Status** (**All Status**, **Open**, **In Progress**, **Resolved**, **Cancelled**); **Priority** (**All Priority**, **Urgent**, **High**, **Medium**, **Low**); **Category** (**All Categories**, **Plumbing**, **Electrical**, **HVAC**, **Appliance**, **Structural**, **Other**).",
      "Table **Maintenance requests**. **Discussion** on the detail pane.",
      "**Open pipeline** — Tasks maintenance board.",
      "No **New ticket** / **Create Request** on this page. No delete button. No export / print / bulk / sort.",
      "Pagination if the list uses it (scroll the table if not).",
      "**Create from elsewhere**",
      "Dashboard / property rail **Maintenance** opens **Create Request** (details, location, priority).",
      "Tenant portal **New ticket**.",
      "Properties → building **Maintenance** tab: **Add Request**, **View all**.",
    ],
  },
  {
    slug: "chase-payments",
    title: "Chase unpaid rent on Tasks",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "After invoices are out. Recording the cash is still **Collect rent** / **Confirm a receipt**.",
    replaces: "A paper follow-up list of who still owes this period.",
    href: "/admin/tasks",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/chase-payments.webm",
    steps: [
      "Sidebar **Tasks** (`/admin/tasks`). Switch to the **Payments** board (not **Onboarding**).",
      "Click **Add rent payment** if a card is missing. Fill **First name**, **Last name**, **Building**, **Unit / room**, **Rent due**, **Amount (₱)**. Click **Create rent follow-up**.",
      "Drag through **Upcoming** → **Due** → **Reminder sent** → **Overdue** → **Paid** (or **Refund** / **Escalation**).",
    ],
    doneWhen: "After refresh the card is in **Paid** when the invoice is collected. Sync if the board looks stale.",
    watchOut: "Do this on **Payments**, not **Onboarding**. Moving a card to **Paid** is follow-up — it does not post a receipt by itself.",
    alsoOnThisPage: [
      "Same chrome as Onboarding: search, **Advanced Filters**, **Import**, **Bulk Actions**, **Configure stages**.",
      "**Rent due date is required.**",
      "**Building expenses** board: **Add bill or expense** — vendor follow-up, not the Expenses ledger.",
      "**Sync pipelines** can refresh cards from leases/invoices/maintenance.",
      "Confirming money: **Payments** hub, not this board.",
    ],
  },
  {
    slug: "file-documents",
    title: "File a contract or ID in Documents",
    categoryId: "day-to-day",
    who: "Office admin",
    when: "You have a file that belongs on the property or tenant, not only on the tenant Documents tab.",
    replaces: "A folder of IDs and contracts, or files sitting in chat.",
    href: "/admin/documents",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/file-documents.webm",
    steps: [
      "Sidebar **Documents** (`/admin/documents`). Click **Upload document**.",
      "Add **Files**, **Document name**, **Category**, **Type**, optional **Property** / **Tenant**, **Expiry date**. Optional camera: **Take document photo**.",
      "Click **Upload** (or **Upload {n} files**).",
    ],
    doneWhen: "After refresh the file is in the list (linked to the tenant/property if you set those). **Download** still works.",
    watchOut: "**Document name** and a file are required. **Not linked** files show under **Unlinked** — attach a tenant or property if you will need to find them later.",
    alsoOnThisPage: [
      "Cards: **Total documents**, **Pending signature**, **Expiring soon**, **Unlinked**.",
      "**Manage Categories** → `/admin/documents/categories`.",
      "**Search** — **Filename, tenant...**",
      "Filters: **Category** (**All Categories**), **Building**, **Status** (**All Status**, **Signed**, **On file**, **Expiring soon**, **Needs review**).",
      "Row: **View**, **Download**, **Edit**, **Delete** (confirm **Delete document?**). Pagination.",
      "Bulk when selected: **Clear selection**, **Categorize**, **Download ZIP**, **Delete**. Dialog **Bulk Categorize Documents**.",
      "No column sort. No print (except tenant-tab / designer).",
      "Sidebar children: **Lease Designer**, **Templates** (designer list). Generating a lease PDF for a tenant is **Issue or store a lease document**.",
    ],
  },
  {
    slug: "check-collections",
    title: "Check who paid this month (unit × month)",
    categoryId: "month-close",
    who: "Office admin / Owner",
    when: "During the month to chase unpaid rooms, or before closing the period.",
    replaces: "The Excel grid of units down the side and months across the top (paid / partial / blank).",
    href: "/admin/reports",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/check-collections.webm",
    steps: [
      "Sidebar **Reports** (`/admin/reports`). Open **Unit × Month Collections** (`/admin/reports/unit-month`).",
      "Set **Start month**, **End month**, and optional **Property** (**All properties** or one building).",
      "Click **Generate matrix**. Green **Paid**, amber **Partial**, red **Unpaid**, grey **Vacant**.",
    ],
    doneWhen: "The grid matches the rooms you expect. Unpaid cells are the follow-up list. After refresh, generate again.",
    watchOut: "**Start month** and **End month** are required. This is a check, not recording a payment — use **Collect rent** or **Confirm a receipt** to change a cell.",
    alsoOnThisPage: [
      "**This report**",
      "Table header **Unit**. No search on the grid. No pagination. No export button on this screen (use **Data Export** from the hub if you need a file).",
      "Admin / owner units are excluded (revenue units only).",
      "Does not save a snapshot — generate again after a refresh.",
      "**Reports hub** (`/admin/reports`)",
      "Search **Report name...**. Category filter **All categories**.",
      "Other financial reports: **Collected Amount Report**, **Disbursement / Cash-flow**, **Portfolio Rollup**, **Deposit Report**, **Expense Report**, **Comprehensive Financial Report**, **Revenue Report**, **Expense Analysis**, **Rent Roll Report**, **Profit & Loss Statement**.",
      "Property: **Vacant Rooms Report**, **Occupancy Report**, **Building Performance**, **Room Status Report**.",
      "Tenant: **Tenant List Report**, **Tenant Summary**, **Payment Patterns**, **Outstanding Balances**.",
      "Asset / Utility / Analytics rows as listed on the hub.",
      "See **Pull a collections or occupancy report**.",
    ],
  },
  {
    slug: "close-month",
    title: "Close the month (disbursement / grand total)",
    categoryId: "month-close",
    who: "Owner / office admin",
    when: "After collections and expenses for the period are in (same window as the old ledger, e.g. 16th–15th).",
    replaces: "The Excel waterfall: collections minus expenses, then cash, deposits, and cheques to a grand total.",
    href: "/admin/reports/disbursement",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/close-month.webm",
    steps: [
      "Sidebar **Reports** → **Disbursement / Cash-flow** (`/admin/reports/disbursement`).",
      "Set **From**, **To**, and optional **Property**. Click **Generate**.",
      "Read **Total Collection − Expenses = Cash Allowance + Deposit cash + Cheques**. Optional: **Print**. Optional: **Lock period to lifetime** only when that period must not be counted again.",
    ],
    doneWhen: "The waterfall numbers match what you expect for the dates. After refresh, click **Generate** again with the same dates to confirm.",
    watchOut: "**From** and **To** are required. Record expenses first or the expense line stays low. **Lock period to lifetime** is permanent from this screen.",
    alsoOnThisPage: [
      "Back: **All reports**.",
      "**Date range** filters. No search of rows. No pagination of the waterfall.",
      "**Print** is on this page. No Excel/PDF export button here.",
      "**Lock period to lifetime** — cannot be undone from this screen (**Period locked** / **Already locked**).",
      "Related: **Collected Amount Report**, **Portfolio Rollup**, **Deposit Report**, **Expense Report** from the Reports hub.",
    ],
  },
  {
    slug: "bills-expenses-reports",
    title: "Export this month’s bills and expenses",
    categoryId: "month-close",
    who: "Owner / office admin",
    when: "Month close, after utility bills and expenses are entered.",
    replaces: "Totalling Meralco, water, and cash-out rows in Excel for the owner.",
    href: "/admin/bills-expenses/reports",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/bills-expenses-reports.webm",
    steps: [
      "Sidebar **Bills & Expenses** → **Reports** (`/admin/bills-expenses/reports`).",
      "Set **Report type** (**Summary by category** or **Detail list**), **Period** (**This month**, **Last month**, **This quarter**, **Last quarter**, **Last 6 months**, **This year**), **Building** (**All buildings** or one).",
      "Click **Generate**. Then **Print**, **PDF**, or **Excel**.",
    ],
    doneWhen: "The table matches the period. After refresh, **Generate** again — this screen does not store a snapshot.",
    watchOut: "**Generate** first or **PDF** / **Excel** will not run. Utility splits and expenses must already be recorded.",
    alsoOnThisPage: [
      "Title **Reports** / **Expense & utility bill reporting**. **Back to Bills & Expenses**.",
      "Empty until **Generate**. Copy: **Choose report type, period, and building, then click Generate.**",
      "No search of individual bills here — that is **Utility Bills** / **Expenses**.",
      "Toast **Report Generated**. Export without generate: **Generate the report first**.",
    ],
  },
  {
    slug: "pull-report",
    title: "Pull a collections or occupancy report",
    categoryId: "month-close",
    who: "Owner / office admin",
    when: "You need a printout or a period total that is not the unit × month desk or the disbursement waterfall.",
    replaces: "Asking the accountant to rebuild Excel pivots for occupancy, deposits, or vacant rooms.",
    href: "/admin/reports",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/pull-report.webm",
    steps: [
      "Sidebar **Reports** (`/admin/reports`). Search **Report name...** or set Category (not **All categories**).",
      "Open the report (names below). Set its date / property filters.",
      "Use **Generate**, **Print**, **Export Excel**, or **Export PDF** if that report shows them.",
    ],
    doneWhen: "The figures match the period you set. After refresh, generate again — most reports do not store a snapshot.",
    watchOut: "Pick the same **From** / **To** (or month range) you use in Excel. Admin units are excluded from some collection views.",
    alsoOnThisPage: [
      "**Hub**",
      "Categories: **Financial Reports**, **Property Reports**, **Tenant Reports**, **Asset Reports**, **Utility Reports**, **Analytics & Insights**.",
      "No bulk. Hub itself has search + category filter only.",
      "**Financial (besides unit × month and disbursement)**",
      "**Collected Amount Report** — received by month/quarter/six months/year (`/admin/reports/collected-amount`).",
      "**Portfolio Rollup** — Balibago vs Villasol occupancy and collections (`/admin/reports/portfolio`).",
      "**Deposit Report** — deposits on hand (`/admin/reports/deposits`).",
      "**Expense Report** — **Export Excel**, **Export PDF**, **Print** (`/admin/reports/expenses`).",
      "**Comprehensive Financial Report** / **Revenue Report** / **Expense Analysis** / **Rent Roll Report** / **Profit & Loss Statement** → `/admin/financial/reports` (and `?type=` variants). Payments child **Reports & Analytics** is the same family.",
      "**Property / tenant**",
      "**Vacant Rooms Report** (`/admin/reports/vacant-rooms`).",
      "**Occupancy Report** / **Building Performance** / **Payment Patterns** → Analytics.",
      "**Room Status Report** → `/admin/rooms` (not in sidebar).",
      "**Tenant List Report** — balances and past due (`/admin/reports/tenant-list`).",
    ],
  },
  {
    slug: "financial-dashboard",
    title: "Read this month’s money at a glance",
    categoryId: "month-close",
    who: "Owner / office admin",
    when: "A quick look at revenue, occupancy, and upcoming dues — not for recording cash.",
    replaces: "Scanning Excel totals without a chart.",
    href: "/admin/financial/dashboard",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/financial-dashboard.webm",
    steps: [
      "Sidebar **Payments** → **Financial Dashboard** (`/admin/financial/dashboard`).",
      "Read the KPI cards and charts (revenue, occupancy, upcoming dues).",
      "Follow a chart or list into **Payments** / **Invoices** if a number looks wrong.",
    ],
    doneWhen: "You can say whether collections and occupancy look normal for the period. Refresh still shows the same KPIs.",
    watchOut: "Charts lag the last payment you just entered until you refresh. This screen does not confirm GCash receipts.",
    alsoOnThisPage: [
      "Type `/admin/financial` for the financial hub (Payments, Invoices, Expenses, Late fees, gateways) — not in the sidebar.",
      "**Reports & Analytics** is a different page (`/admin/financial/reports`).",
      "**Advanced Financial Analytics** (`/admin/financial/advanced-analytics`) — deeper benchmarks.",
      "No Process Payment button required on this dashboard — recording cash is **Collect rent**.",
      "No export on the dashboard itself.",
    ],
  },
  {
    slug: "export-data",
    title: "Export a spreadsheet for the accountant",
    categoryId: "month-close",
    who: "Owner / office admin",
    when: "The accountant needs CSV / Excel / PDF / JSON. Open from Reports hub **Data Export**, or Settings → System **Export Data**. URL `/admin/export`.",
    replaces: "Copy-paste from Excel into another workbook.",
    href: "/admin/export",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/export-data.webm",
    steps: [
      "Open **Advanced Export** (`/admin/export`).",
      "Choose the data set and format (**CSV**, **Excel**, **PDF**, or **JSON** as offered).",
      "Run the export and save the file.",
    ],
    doneWhen: "The file opens with the rows you expect. Re-run after a refresh if you just recorded payments.",
    watchOut: "Pick the same date range as the ledger. A PDF of the wrong module is not a substitute for **Disbursement / Cash-flow**.",
    alsoOnThisPage: [
      "Not in the sidebar. Custom column/format options live on this page.",
      "Some reports have their own **Export Excel** / **Export PDF** / **Print** (Expense Report, Bills & Expenses Reports, tenant **Statements**).",
      "Payments list has **no** export.",
    ],
  },
  {
    slug: "unit-groups",
    title: "Name a unit group for shared bills",
    categoryId: "utilities-property",
    who: "Office admin",
    when: "Before splitting a bill that is not the whole building (e.g. Balibago 3rd-floor water).",
    replaces: "Remembering “3rd floor shares one water meter” in a notebook.",
    href: "/admin/bills-expenses/unit-groups",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/unit-groups.webm",
    steps: [
      "Sidebar **Bills & Expenses** → **Unit groups** (`/admin/bills-expenses/unit-groups`).",
      "**New group:** **Building**, **Name** (e.g. Balibago 3rd floor water), **Utility type** (**Water**, **Electricity**, **Any / unspecified**). Tick member rooms. Optional **Add floor {n}**.",
      "Click **Create group**. On **Add Bill**, choose that group under **Unit group (preferred)**.",
    ],
    doneWhen: "After refresh the group is under **Active groups**. Equal-split **Add Bill** can select it.",
    watchOut: "**Building and name are required.** **Deactivate** does not ask for confirmation.",
    alsoOnThisPage: [
      "Filter **All buildings**. **Edit group** / **Update group**. **Deactivate** (immediate — no confirm; hides from the active list).",
      "**Cancel**. **Members ({n})**. **Description**.",
      "No search. No sort. No pagination. No export. No hard Delete.",
      "Empty: **No unit groups yet**.",
    ],
  },
  {
    slug: "enter-meter-readings",
    title: "Enter this month’s meter readings",
    categoryId: "utilities-property",
    who: "Office admin",
    when: "After you walk the meters, before a usage-based split.",
    replaces: "A paper log of electric/water meter numbers at each building.",
    href: "/admin/utilities/readings",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/enter-meter-readings.webm",
    steps: [
      "Sidebar **Utilities** → **Meter Readings** (`/admin/utilities/readings`). Click **Add Reading** (or **Add Meter Reading**).",
      "**Building**, **Utility Type**, **Reading Date**, **Reading Value**. Optional: **Meter Number (optional)**, **Notes (optional)**.",
      "Click **Save Reading**.",
    ],
    doneWhen: "After refresh the reading is in the table. **Cost Allocation** can use it for usage-based split.",
    watchOut: "**Building** is required. There is no **Edit** — enter a new reading if you typed the wrong value.",
    alsoOnThisPage: [
      "Cards: **Total Readings**, **Unique Meters**, **This Month**, **Buildings**.",
      "**Search** — **Building, meter, utility...**",
      "Filters: **Building** (**All Buildings**); **Utility** (**All Types**, **Electricity**, **Water**, **Gas**, **Internet**, **Other**).",
      "**Cancel** on the form.",
      "No edit/delete of a reading. No sort / pagination / bulk / export / print.",
      "Empty: **Get started by adding your first meter reading.**",
      "Older **Utilities Management** at `/utilities` (from Reports → **Utility Bills Summary**) is a different dashboard.",
    ],
  },
  {
    slug: "split-metered-bill",
    title: "Split a metered bill by readings",
    categoryId: "utilities-property",
    who: "Office admin",
    when: "You have a total bill and meter readings, and equal-split on Utility Bills is not enough.",
    replaces: "Spreadsheet formulas that divide one bill using last month’s meter numbers.",
    href: "/admin/utilities/cost-allocation",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/split-metered-bill.webm",
    steps: [
      "Sidebar **Utilities** → **Cost Allocation** (`/admin/utilities/cost-allocation`). Choose **Building**.",
      "**Allocation Rules:** set **Utility Type**, **Allocation Method**, optional **Include Common Area Costs**. **Save Rule**.",
      "**Cost Calculator:** **Select Utility Bill**, method (**Equal Split**, **Usage-Based**, **Room Size**, **Custom Rules**), **Tenant Bill Due Date**. Click **Calculate Allocation**, then **Generate Tenant Bills**.",
    ],
    doneWhen: "After refresh **Tenant Bills** lists a row per tenant. Amounts match the calculator.",
    watchOut: "Pick a building first. Usage-based needs meter readings. **Generate Tenant Bills** is separate from **Calculate Allocation** — calculate first.",
    alsoOnThisPage: [
      "Tabs: **Overview**, **Allocation Rules**, **Cost Calculator**, **Tenant Bills**.",
      "Building search **Building name or address...** Empty: **Select a Building**.",
      "Overview explains **1. Configure Rules**, **2. Calculate Costs**, **3. Generate Bills**.",
      "**Tenant Bills:** search **Search tenant, room, utility...**; filters; **Mark as Sent** / **Mark as Paid** / **Mark as Overdue** / **Update Status**.",
      "No export/print on these tabs.",
      "Building-wide equal-split without meters is **Split a utility bill across rooms**.",
    ],
  },
  {
    slug: "log-assets",
    title: "Log furniture and appliances in a unit",
    categoryId: "utilities-property",
    who: "Office admin",
    when: "You buy or move an asset, or need a QR for on-site checks.",
    replaces: "A paper inventory of beds, ACs, and appliances per room.",
    href: "/admin/assets",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/log-assets.webm",
    steps: [
      "Sidebar **Assets** (`/admin/assets`). Click **Add Asset**.",
      "Fill **Asset Name**, **Asset Type**. Optional: **Brand**, **Model**, **Serial Number**, **Building**, **Status**, **Condition**, **Purchase Price**, **Current Value**, **Rental Rate (per month)**, **Description**. Click **Save Asset**.",
      "Optional: tab **QR Codes** to print a code. Scan later at `/track/asset/[id]`.",
    ],
    doneWhen: "After refresh the asset is in **Asset Overview**. **Export** can download the list. Edit later with **Update Asset**.",
    watchOut: "**Asset Name** and **Asset Type** are required. The add form has **Building**, not a room picker. **Disposed** is not the same as delete.",
    alsoOnThisPage: [
      "Header **Export**, **Add Asset**.",
      "Tabs: **Asset Overview**, **Maintenance Schedule**, **Analytics**, **QR Codes**.",
      "**Search** — **Name, brand, serial...**",
      "Filters: **Building**; **Status** (**All Status**, **Available**, **Assigned**, **Maintenance**, **Disposed**); **Condition** (**All Conditions**, **Excellent**, **Good**, **Fair**, **Poor**, **Damaged**).",
      "Delete confirms before remove.",
      "Public scan page is outside admin. `?scan=true` writes a scan note.",
      "Reports hub **Asset Inventory** / **Asset Assignment Report** open this module.",
    ],
  },
  {
    slug: "lease-templates",
    title: "Set lease template terms (deposit, term, penalty)",
    categoryId: "setup",
    who: "Office admin",
    when: "Before assigning rooms — Add Tenant and the pipeline pick from this list.",
    replaces: "A note in Excel of “2 months deposit, 1 month advance” copied onto every new occupant.",
    href: "/admin/lease-templates",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/lease-templates.webm",
    steps: [
      "Sidebar **Leasing** → **Lease Templates** (`/admin/lease-templates`). Click **Create Lease Template**.",
      "Fill **Template Name**, **Lease Term** (3 / 6 / 12 Months / No Fixed Term), **Deposit Period**, **Advance Period**. Optional: **Grace Period (optional)**, **Penalty Type**, **Penalty Fee**.",
      "Click **Confirm and Save**. On edit: **Save Changes**.",
    ],
    doneWhen: "After refresh the template is in the list. Add Tenant **Lease Template** dropdown shows it.",
    watchOut: "**Template Name** is required. Do not delete a template still assigned to units.",
    alsoOnThisPage: [
      "Search **Template name...** Filter **Applied**: **All templates**, **Assigned to units**, **Unused**.",
      "Row: **View**, **Edit**, **Delete**. Confirm **Confirm Deletion** — cannot be undone. **Unable to Delete** if still in use.",
      "This is not **Lease Designer** (PDF layout) and not **Documents → Templates**.",
    ],
  },
  {
    slug: "design-lease",
    title: "Design the lease PDF the office generates",
    categoryId: "setup",
    who: "Admin",
    when: "The 1-page room rental agreement needs new clauses before you **Generate lease** for tenants.",
    replaces: "Editing a Word contract by hand every time the house rules change.",
    href: "/admin/documents/lease-designer",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/design-lease.webm",
    steps: [
      "Sidebar **Documents** → **Lease Designer** (`/admin/documents/lease-designer`).",
      "Edit **Clauses** (**Add clause**, **Text clause** / **Checkbox options** / **Utility allocation table**). Optional **Use compact template** (replaces all clauses with the compact Room Rental Agreement).",
      "Click **Save draft** or **Publish…**. Check **Printable preview**; **Print** or **Export PDF**.",
    ],
    doneWhen: "After refresh the template still shows your clauses. The next **Generate lease** on a tenant uses this layout.",
    watchOut: "**Use compact template** wipes unsaved edits. Publish only when the office agrees the wording is final.",
    alsoOnThisPage: [
      "Page size **US Letter** / **A4**. Badges **Unsaved**, **V{n} · Published** / **Draft**.",
      "**Signatures** — **Print Name:**, **Upload image**. **Remove clause**.",
      "**Export Word** may show a stub message (PDF/print are the reliable outputs).",
      "Confirm **Use compact template** — unsaved edits are lost.",
      "**Documents** → **Templates** (`/admin/documents/templates`): search **Template name...**; **All Status** / **Published** / **Draft**; **Open Lease Designer**; **View**.",
      "Package terms (deposit months, grace, penalty) are **Lease Templates** under Leasing, not this designer.",
    ],
  },
  {
    slug: "document-categories",
    title: "Set document categories",
    categoryId: "setup",
    who: "Admin",
    when: "Before filing IDs and contracts, if **Uncategorized** is not enough.",
    replaces: "Folder names on a shared drive.",
    href: "/admin/documents/categories",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/document-categories.webm",
    steps: [
      "Sidebar **Documents** → **Manage Categories** (`/admin/documents/categories`). Title **Document Categories**.",
      "Click **New Category**. Fill **Category Name** (required). Optional: **Description**, **Parent Category (optional)** (**No parent (root category)**).",
      "Click **Create Category**. Return to **Documents** and use **Category** on upload and filters.",
    ],
    doneWhen: "After refresh the new name is in the list and in the Documents **Category** filter.",
    watchOut: "**Category Name** cannot be blank (**Create Category** stays off until it has text). There is no delete on this screen if you add a name by mistake.",
    alsoOnThisPage: [
      "Copy: **Organize your documents with categories for easier management and searching.**",
      "Empty: **No categories yet** / **Create Category**.",
      "List shows document count and **Created** date; nested names under a parent.",
      "No search, filter, sort, pagination, export, or print.",
      "**No Edit or Delete on this page** — you can only add categories here.",
      "Upload default **Uncategorized**. Library bulk **Categorize**.",
    ],
  },
  {
    slug: "office-settings",
    title: "Set office preferences",
    categoryId: "setup",
    who: "Admin",
    when: "First week on the app, and when you turn the tenant portal or late fees on or off.",
    replaces: "TBD - ask client (portal on/off, late fees, reminders were not in the Excel ledger).",
    href: "/admin/settings",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/office-settings.webm",
    steps: [
      "Header gear → **Settings** (`/admin/settings`). (Not a sidebar item except **Tenant pay details**.)",
      "**System:** tick **Enable tenant portal** if tenants will log in. Leave **Enable late-fee penalties** off unless you will use **Apply Late Fees**.",
      "Click **Save Settings**. For GCash numbers use tab **Tenant payments** (separate job).",
    ],
    doneWhen: "After refresh the same checkboxes are still set. Tenants can open `/auth/signin` only if **Enable tenant portal** is on.",
    watchOut: "**Enable late-fee penalties** is off by default. Turning it on without running Apply Late Fees does not charge anyone by itself.",
    alsoOnThisPage: [
      "Tabs: **Notifications**, **Security**, **Preferences**, **Tenant payments**, **System**.",
      "**Notifications** — **Notification categories**; **In-app** / **Email** toggles.",
      "**Security** — **Two-Factor Authentication**, **Session Timeout** (15 min–8 hours), **Change Password**.",
      "**Preferences** — Language, Timezone, Currency, Date Format.",
      "**System** — **Nearby map** / **Cached street-route lifetime (days)** / **Replace all catalogs from OpenStreetMap**; **System Information**; **Clear Cache**; **Export Data**.",
      "No search. Branding/SMTP/role matrix are not on this page.",
    ],
  },
  {
    slug: "add-office-login",
    title: "Add an office login",
    categoryId: "setup",
    who: "Office admin (owner)",
    when: "A new staff member needs the app.",
    replaces: "Sharing one Excel / Gmail login among the office.",
    href: "/admin/users",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/add-office-login.webm",
    steps: [
      "Sidebar **Users** (`/admin/users`). Click **Create Admin**.",
      "In **Create portal account** fill **First name**, **Last name**, **Email**, **Password**, and **Confirm password**. Optional: **Username**. Office accounts are full admin.",
      "Click **Create Account**. Give them **Email** (or username) + password and `/auth/signin`.",
    ],
    doneWhen: "They appear under **Admin Users** as **Active**. After refresh they can sign in.",
    watchOut: "**Password** must be at least 8 characters and match **Confirm password**. This is not a tenant portal login — use **Add Tenant** for that. There is no separate caretaker role.",
    alsoOnThisPage: [
      "Title **Admin Users**. Cards: **Total Admins**, **Active**, **Inactive**, **Showing**.",
      "**Search** — **Name, email, username...**",
      "**Status** filter: **All Status**, **Active**, **Inactive**.",
      "Pagination 20 per page.",
      "Row: **Edit**, **Deactivate** / **Activate**. Edit dialog **Edit Admin User** (can set password).",
      "No hard Delete. No export. No permissions matrix. No staff-role create on this page.",
      "**Deactivate** is not available on your own active account.",
      "Footer avatar → **Admin Profile** to change *your* password (see **Change my office password**).",
      "Staff who only work repairs use `/staff` — a different login, not this page.",
    ],
  },
  {
    slug: "change-office-password",
    title: "Change my office password",
    categoryId: "setup",
    who: "Office admin (your own account)",
    when: "First login, or when you need a new password.",
    replaces: "Sharing one password on a sticky note.",
    href: "/admin/profile",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/change-office-password.webm",
    steps: [
      "Sidebar footer (your name/avatar) → `/admin/profile`. Or Settings → **Security** → **Change Password**.",
      "On **Admin Profile**, edit name/photo if needed. Click **Save Changes**. Under **Change Password**, enter current and new passwords.",
      "Click **Change Password**.",
    ],
    doneWhen: "After **Sign out**, you can **Login** with the new password.",
    watchOut: "New password must meet the form’s length rule and match confirm. Changing *your* password does not change tenant portal passwords.",
    alsoOnThisPage: [
      "Profile photo. Name fields.",
      "Settings **Security** also has **Two-Factor Authentication** and **Session Timeout**.",
      "To reset someone else’s office login: **Users** → **Edit**.",
      "To reset a tenant: tenant profile **Reset password**.",
      "Forgot from sign-in: **Forgot Password?** → `/auth/forgot-password`.",
    ],
  },
  {
    slug: "look-up-activity",
    title: "Look up who changed a record",
    categoryId: "setup",
    who: "Admin",
    when: "A payment, tenant, or lease looks wrong and you need the history.",
    replaces: "Asking “who edited Excel?” with no trail.",
    href: "/admin/activity",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/look-up-activity.webm",
    steps: [
      "Sidebar **Activity** (`/admin/activity`).",
      "**Search** **Entity name...** Set **Category**, **Action type** (e.g. tenant.created), **From**, **To**.",
      "Open a row’s **Details**. Use **Previous** / **Next** if paginated.",
    ],
    doneWhen: "You can name who did the change and when. After refresh the same event is still listed.",
    watchOut: "Filters are exact — if **Action type** is wrong, the list looks empty. This page does not undo a change.",
    alsoOnThisPage: [
      "Stats: total events / this page / category / selected.",
      "No bulk. No export/print on this feed.",
      "Staff portal **Activity Logs** may open `/admin/activity-logs` (redirects to Activity).",
    ],
  },
  {
    slug: "send-reminders",
    title: "Send payment reminder emails",
    categoryId: "setup",
    who: "Admin",
    when: "After invoices are out and some units are still unpaid.",
    replaces: "Chasing unpaid rent one by one on Messenger.",
    href: "/admin/notifications",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/send-reminders.webm",
    steps: [
      "Open **Email Reminders** (`/admin/notifications`). There is no sidebar item — Dashboard notifications “view all”, or type the URL.",
      "Under **Generate Payment Reminders**, click **Generate Reminders**.",
      "Under **Process Notification Queue**, click **Process Queue**.",
    ],
    doneWhen: "Reminders are generated and the queue processes without an error. Tenants who should get email have an address on file.",
    watchOut: "This is easy to miss (not in the sidebar). Generating without **Process Queue** leaves mail sitting. Tenants without email will not get a message.",
    alsoOnThisPage: [
      "Section **How Notifications Work**.",
      "Header bell is **not** this page (bell → Settings → Notifications).",
      "No inbox, no compose, no template editor here.",
      "Settings **Notifications** tab only toggles In-app / Email categories.",
    ],
  },
  {
    slug: "caretaker",
    title: "What a caretaker can (and cannot) do",
    categoryId: "occasional",
    who: "Office admin",
    when: "You are looking for a limited caretaker login. That role was withdrawn.",
    replaces: "",
    href: "/admin/users",
    hasVideo: false,
    videoSrc: null,
    steps: [
      "Caretaker is not a separate office role. Create an office login with **Add an office login**. They get the same admin access as everyone else (Dashboard, Payments, Reports, Users).",
      "Staff who should only work repairs still use the **Staff** portal (`/staff`), which is a different role — not caretaker.",
    ],
    doneWhen: "The person either has an office login on **Users**, or they sign in at `/staff` to work the repair queue.",
    watchOut: "Do not look for a caretaker option on **Users**. Office accounts are admin.",
    alsoOnThisPage: [
    ],
  },
  {
    slug: "generate-all-invoices",
    title: "Generate all rent invoices for the month",
    categoryId: "occasional",
    who: "Admin",
    when: "You would otherwise click **Create Invoice** once per tenant. Not in the sidebar — `/admin/bulk-operations` (linked from History import).",
    replaces: "Copying one Excel rent row per occupied unit at period start.",
    href: "/admin/bulk-operations",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/generate-all-invoices.webm",
    steps: [
      "Open **Bulk Operations** (`/admin/bulk-operations`). Tab **Generate Invoices**.",
      "Set **Target Month**. Optional **Building Filter (Optional)**.",
      "Click **Generate Invoices for All Tenants**.",
    ],
    doneWhen: "After refresh, **Payments** → **Invoices** shows a rent invoice per active tenant for that month (skipping ones that already exist, if the tool is idempotent).",
    watchOut: "Wrong **Target Month** bills the wrong period. This does not collect money. Prefer one-by-one **Create Invoice** if you only have a few rooms.",
    alsoOnThisPage: [
      "Link **History import**.",
      "Tabs: **Generate Invoices**, **Import Payments**, **Update Tenants**.",
      "**Import Payments** — CSV of payments.",
      "**Update Tenants** — tenant IDs + **New Status** **Active** / **Former / inactive**; **Update Tenant(s) to …**",
      "No search of a live invoice grid here — check **Invoices** after.",
    ],
  },
  {
    slug: "import-history",
    title: "Import old Excel history",
    categoryId: "occasional",
    who: "Admin",
    when: "One-time (or rare) load of past payments, expenses, tenants+assignments, or meter readings. Not in the sidebar — `/admin/tools/history-import`.",
    replaces: "Re-typing years of Excel payments and occupancy into the app by hand.",
    href: "/admin/tools/history-import",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/import-history.webm",
    steps: [
      "Open **Historical data migration**. Back link **Bulk operations**.",
      "**Import setup:** pick **Data type** (**Payments / collections**, **Expenses**, **Tenants + room assignments**, **Utility meter readings**). **Download CSV template**, fill it, **Upload CSV** or paste **CSV content**.",
      "Click **Preview (dry-run)**. Only if the preview looks right: **Commit import**.",
    ],
    doneWhen: "Preview counts match the spreadsheet. After commit and refresh, sample rows appear on Payments / Expenses / Tenants / Meter Readings.",
    watchOut: "**Commit import** cannot be casually undone. A bad CSV can duplicate payments. Never skip **Preview (dry-run)**.",
    alsoOnThisPage: [
      "Always dry-run first. Commit writes for real.",
      "Linked from Bulk Operations. No list search of existing records on this page.",
      "Occupancy names from the Start & End Date sheet are a different office process — ask before using this for dummy **Tenant Unit N** rows.",
    ],
  },
  {
    slug: "late-fees",
    title: "Turn on and apply late fees",
    categoryId: "occasional",
    who: "Owner / office admin",
    when: "You have decided to charge overdue rent. Off by default — prefer **Negotiate due date** on the invoice.",
    replaces: "TBD - ask client (Excel ledger did not run automatic penalties).",
    href: "/admin/financial/late-fees/settings",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/late-fees.webm",
    steps: [
      "Settings → **System**: tick **Enable late-fee penalties**. **Save Settings**.",
      "Open `/admin/financial/late-fees/settings` (from the financial hub **Late fees**, not the sidebar). Save penalty rules.",
      "Open `/admin/financial/late-fees/apply`. **Calculate Eligible Fees**, then **Apply Late Fees**. Confirm **Apply late fees?**",
    ],
    doneWhen: "After refresh, overdue invoices show the fee and **Payments** Type **Penalty** can collect it.",
    watchOut: "If **Enable late-fee penalties** is off, Apply will not charge. **Apply Late Fees** is not a dry run — use **Dry run** first.",
    alsoOnThisPage: [
      "Apply page title **Late Fee Application**. **Dry run** before apply.",
      "Alert **Late fees are disabled** if the System checkbox is off.",
      "Invoice detail: **No late-fee penalties — agree a new deadline when rent is delayed, or apply a discretionary discount.**",
      "Payment gateways are a different hub card (**Test Mode**).",
    ],
  },
  {
    slug: "payment-gateways",
    title: "Set up online pay (gateways)",
    categoryId: "occasional",
    who: "Admin",
    when: "Only if you will turn on a real payment gateway. Otherwise skip this job.",
    replaces: "TBD - ask client (live card checkout was not how Alfonso collected rent).",
    href: "/admin/financial",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/payment-gateways.webm",
    steps: [
      "Open the financial hub `/admin/financial` → **Payment gateways** (`/admin/financial/payment-gateways`). Not under Payments children.",
      "Review **Payment Gateway Configuration**. Badge **Test Mode**.",
      "**Save Configuration** only after the owner agrees. Keep **Test Mode** on until go-live.",
    ],
    doneWhen: "If you must use this: after refresh **Test Mode** still matches what you saved. For day-to-day Alfonso collection, **Tenant pay details** is the done state instead.",
    watchOut: "Saving live keys in **Test Mode** will not take real tenant card payments. Prefer GCash + **Confirm payment**.",
    alsoOnThisPage: [
      "Cards: **Active Gateways**, **Payment Methods**, **Avg Processing Fee**, **Webhooks Status**.",
      "Settings labels: **Currency**, **Test Mode**, **Require CVV**, **Allow Save Card**, **Auto-capture Payments**, **Enable Recurring Payments**.",
      "**Back**. **Test Mode Active**.",
      "This does not replace **Payment phone number** on Pay online.",
    ],
  },
  {
    slug: "staff-portal",
    title: "Sign in as staff and work the repair queue",
    categoryId: "occasional",
    who: "Staff (not an office admin login)",
    when: "Maintenance should be done without full office access.",
    replaces: "A caretaker walking units with a paper list of repairs.",
    href: "/auth/staff/signin",
    hasVideo: true,
    videoSrc: "/knowledge-base/videos/staff-portal.webm",
    steps: [
      "Open `/staff` (staff sign-in `/auth/staff/signin` goes to the same **Login**).",
      "**Staff Portal** → **Operations**: **Maintenance Queue** (`/admin/maintenance`), **Rooms** (`/admin/rooms`), **Activity Logs**.",
      "Work tickets as in **Work a repair ticket**.",
    ],
    doneWhen: "You can open the maintenance queue and save a ticket status. After refresh the status holds.",
    watchOut: "This is not a limited “caretaker” office role — caretaker was withdrawn. If they need Payments and Reports, create an office login instead.",
    alsoOnThisPage: [
      "Header **Staff Portal**. Admin note may offer **open Admin Dashboard** if the account is admin.",
      "No separate staff maintenance UI — it reuses the office screens.",
      "Not linked from the admin sidebar. Office logins are created on **Users** as admin, not staff.",
    ],
  },
];

for (const article of KNOWLEDGE_ARTICLES) {
  if (article.slug === 'caretaker') {
    article.hasVideo = false;
    article.videoSrc = null;
    article.youtubeId = null;
    continue;
  }
  article.youtubeId = parseYouTubeId(KNOWLEDGE_YOUTUBE_IDS[article.slug] || '');
  article.videoSrc =
    article.youtubeId || process.env.NODE_ENV === 'production'
      ? null
      : `/knowledge-base/videos/${article.slug}.webm`;
  article.hasVideo = Boolean(article.youtubeId || article.videoSrc);
}

export function getKnowledgeArticle(slug: string): KnowledgeArticle | undefined {
  return KNOWLEDGE_ARTICLES.find((article) => article.slug === slug);
}

export function articlesInCategory(categoryId: string): KnowledgeArticle[] {
  return KNOWLEDGE_ARTICLES.filter((article) => article.categoryId === categoryId);
}

export const RECORDED_ARTICLES = KNOWLEDGE_ARTICLES.filter((article) => article.hasVideo);

export function articleKindLabel(article: KnowledgeArticle): string {
  return article.hasVideo ? 'Video' : 'Guide';
}

export interface KnowledgeModule {
  id: string;
  title: string;
  description: string;
  slugs: string[];
}

/** Product modules on the Knowledge base home (Properties, Tenants, Leasing, …). */
export const KNOWLEDGE_MODULES: KnowledgeModule[] = [
  {
    id: 'properties',
    title: 'Properties',
    description: 'Buildings, rooms, holds, and unit extras',
    slugs: ['add-unit', 'hold-unit', 'log-assets', 'unit-groups'],
  },
  {
    id: 'tenants',
    title: 'Tenants',
    description: 'People, occupants, portal, and how they pay',
    slugs: ['add-tenant', 'add-occupant', 'tenant-portal', 'tenant-pay-details'],
  },
  {
    id: 'leasing',
    title: 'Leasing',
    description: 'Pipeline, leases, notice, renewals, and move-out',
    slugs: [
      'lead-to-tenant',
      'start-lease',
      'issue-lease',
      'lease-templates',
      'design-lease',
      'give-notice',
      'renew-lease',
      'leasing-alerts',
      'move-out',
    ],
  },
  {
    id: 'payments',
    title: 'Payments',
    description: 'Invoices, collecting rent, and chasing unpaid balances',
    slugs: [
      'create-invoice',
      'collect-rent',
      'confirm-receipt',
      'chase-payments',
      'generate-all-invoices',
      'send-reminders',
      'late-fees',
      'payment-gateways',
    ],
  },
  {
    id: 'bills',
    title: 'Bills & utilities',
    description: 'Shared bills, expenses, and meter splits',
    slugs: [
      'utility-bill',
      'record-expense',
      'bills-expenses-reports',
      'enter-meter-readings',
      'split-metered-bill',
    ],
  },
  {
    id: 'documents',
    title: 'Documents',
    description: 'Filing contracts, IDs, and categories',
    slugs: ['file-documents', 'document-categories'],
  },
  {
    id: 'reports',
    title: 'Reports',
    description: 'Dashboard, collections, close-month, and exports',
    slugs: [
      'open-dashboard',
      'check-collections',
      'close-month',
      'pull-report',
      'financial-dashboard',
      'export-data',
    ],
  },
  {
    id: 'maintenance',
    title: 'Maintenance',
    description: 'Repair tickets and the staff queue',
    slugs: ['work-repair', 'staff-portal'],
  },
  {
    id: 'office',
    title: 'Office setup',
    description: 'Logins, settings, activity, and history import',
    slugs: [
      'office-settings',
      'add-office-login',
      'change-office-password',
      'look-up-activity',
      'import-history',
      'caretaker',
    ],
  },
];

export function articlesInModule(moduleId: string): KnowledgeArticle[] {
  const module = KNOWLEDGE_MODULES.find((row) => row.id === moduleId);
  if (!module) return [];
  return module.slugs
    .map((slug) => getKnowledgeArticle(slug))
    .filter((article): article is KnowledgeArticle => Boolean(article));
}

export function moduleForArticle(slug: string): KnowledgeModule | undefined {
  return KNOWLEDGE_MODULES.find((row) => row.slugs.includes(slug));
}

export function getAdjacentArticles(slug: string): {
  previous: KnowledgeArticle | null;
  next: KnowledgeArticle | null;
} {
  const module = moduleForArticle(slug);
  const list = module ? articlesInModule(module.id) : KNOWLEDGE_ARTICLES;
  const index = list.findIndex((article) => article.slug === slug);
  if (index < 0) return { previous: null, next: null };
  return {
    previous: list[index - 1] || null,
    next: list[index + 1] || null,
  };
}
